# Generated by Django 5.2.8 on 2025-11-23 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HuntInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=50)),
                ('distance_nm', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('east', 'East'), ('west', 'West'), ('south', 'South'), ('north', 'North'), ('north-east', 'North-East'), ('north-west', 'North-West'), ('south-east', 'South-East'), ('south-west', 'South-West')], max_length=20)),
                ('distance_nm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=255)),
                ('risk_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_instructions', to='pirateApp.instruction')),
            ],
        ),
    ]
