# Generated by Django 5.2.8 on 2025-11-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirateApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
