# Generated by Django 5.2.8 on 2025-11-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirateApp', '0002_delete_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('is_correct', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
