# Generated by Django 5.2.8 on 2025-11-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirateApp', '0003_passwordguess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huntinstruction',
            old_name='distance_nm',
            new_name='distance_m',
        ),
        migrations.RemoveField(
            model_name='passwordguess',
            name='is_correct',
        ),
    ]
